### ISSUE TITLE
Show arrows on board UI

### ISSUE THREAD

**Issue by Dillon-Roller** [Event-Horizon-Technologies/chess#145]

**Comment by DanielAlbl** [comment]
I find myself drawing arrows to the wrong squares constantly. I had the idea that maybe we could assume you are trying to draw an arrow to squares that are valid moves, even if you land slightly outside it.

**Comment by Dillon-Roller** [comment]
> I find myself drawing arrows to the wrong squares constantly. I had the idea that maybe we could assume you are trying to draw an arrow to squares that are valid moves, even if you land slightly outside it. 

Damn yeah that makes sense
